package com.uri.lee.dl.core.designsystem.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

// Botanical palette: leaf-green primary, sage secondary, turmeric-amber tertiary (confidence and
// highlights), warm off-white surfaces. Tones follow Material 3's roles so contrast stays WCAG AA.

internal val LightColors = lightColorScheme(
    primary = Color(0xFF2F6A3E),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFB4F1BC),
    onPrimaryContainer = Color(0xFF00210B),
    secondary = Color(0xFF516351),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFD4E8D1),
    onSecondaryContainer = Color(0xFF0F1F11),
    tertiary = Color(0xFF855400),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFFFDDB3),
    onTertiaryContainer = Color(0xFF2A1800),
    error = Color(0xFFBA1A1A),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFFFDAD6),
    onErrorContainer = Color(0xFF410002),
    background = Color(0xFFFBF9F3),
    onBackground = Color(0xFF1B1C18),
    surface = Color(0xFFFBF9F3),
    onSurface = Color(0xFF1B1C18),
    surfaceVariant = Color(0xFFDEE5D9),
    onSurfaceVariant = Color(0xFF424940),
    outline = Color(0xFF72796F),
    outlineVariant = Color(0xFFC2C9BD),
    inverseSurface = Color(0xFF30312C),
    inverseOnSurface = Color(0xFFF2F1EA),
    inversePrimary = Color(0xFF98D5A1),
    surfaceContainerLowest = Color(0xFFFFFFFF),
    surfaceContainerLow = Color(0xFFF5F3ED),
    surfaceContainer = Color(0xFFEFEEE7),
    surfaceContainerHigh = Color(0xFFE9E8E2),
    surfaceContainerHighest = Color(0xFFE4E2DC),
)

internal val DarkColors = darkColorScheme(
    primary = Color(0xFF98D5A1),
    onPrimary = Color(0xFF003916),
    primaryContainer = Color(0xFF145129),
    onPrimaryContainer = Color(0xFFB4F1BC),
    secondary = Color(0xFFB8CCB5),
    onSecondary = Color(0xFF243425),
    secondaryContainer = Color(0xFF3A4B3A),
    onSecondaryContainer = Color(0xFFD4E8D1),
    tertiary = Color(0xFFFFB951),
    onTertiary = Color(0xFF462A00),
    tertiaryContainer = Color(0xFF653E00),
    onTertiaryContainer = Color(0xFFFFDDB3),
    error = Color(0xFFFFB4AB),
    onError = Color(0xFF690005),
    errorContainer = Color(0xFF93000A),
    onErrorContainer = Color(0xFFFFDAD6),
    background = Color(0xFF12140F),
    onBackground = Color(0xFFE3E3DB),
    surface = Color(0xFF12140F),
    onSurface = Color(0xFFE3E3DB),
    surfaceVariant = Color(0xFF424940),
    onSurfaceVariant = Color(0xFFC2C9BD),
    outline = Color(0xFF8C9388),
    outlineVariant = Color(0xFF424940),
    inverseSurface = Color(0xFFE3E3DB),
    inverseOnSurface = Color(0xFF30312C),
    inversePrimary = Color(0xFF2F6A3E),
    surfaceContainerLowest = Color(0xFF0D0F0B),
    surfaceContainerLow = Color(0xFF1B1C18),
    surfaceContainer = Color(0xFF1F201C),
    surfaceContainerHigh = Color(0xFF292A26),
    surfaceContainerHighest = Color(0xFF343531),
)
