#!/usr/bin/env python3
"""Writes iosApp/Configuration/Secrets.xcconfig (git-ignored) from files you already have:

  - iosApp/iosApp/GoogleService-Info.plist (Firebase console > Project settings > iOS app):
    REVERSED_CLIENT_ID, the URL scheme Google sign-in returns through
  - local.properties (or the environment, in CI): PHOTO_UPLOAD_URL, the photo-upload Worker (same as Android)

Run it again after downloading a new GoogleService-Info.plist.
"""

import os
import plistlib
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PLIST = os.path.join(ROOT, "iosApp/iosApp/GoogleService-Info.plist")
OUT = os.path.join(ROOT, "iosApp/Configuration/Secrets.xcconfig")


def local_property(name):
    path = os.path.join(ROOT, "local.properties")
    if not os.path.exists(path):
        return os.environ.get(name, "")
    for line in open(path, encoding="utf-8"):
        key, _, value = line.partition("=")
        if key.strip() == name:
            return value.strip()
    return os.environ.get(name, "")


def main():
    if not os.path.exists(PLIST):
        sys.exit("error: %s is missing. Download it from the Firebase console first." % PLIST)
    with open(PLIST, "rb") as f:
        firebase = plistlib.load(f)
    reversed_client_id = firebase.get("REVERSED_CLIENT_ID")
    if not reversed_client_id:
        sys.exit("error: the plist has no REVERSED_CLIENT_ID. Enable Google sign-in in Firebase Auth, then download it again.")
    upload = local_property("PHOTO_UPLOAD_URL")
    # xcconfig treats // as a comment, so the scheme is added in Info.plist
    host = upload.split("://", 1)[-1].rstrip("/")
    with open(OUT, "w", encoding="utf-8") as f:
        f.write("// Generated by tools/ios_secrets.py; not committed.\n")
        f.write("GOOGLE_REVERSED_CLIENT_ID = %s\n" % reversed_client_id)
        f.write("PHOTO_UPLOAD_HOST = %s\n" % host)
    print("Wrote %s" % os.path.relpath(OUT, ROOT))


if __name__ == "__main__":
    main()
