import java.util.Properties
import org.commonmark.parser.Parser
import org.commonmark.renderer.html.HtmlRenderer

buildscript {
    dependencies { classpath(libs.commonmark) }
}

plugins {
    alias(libs.plugins.kotlin.multiplatform)
    alias(libs.plugins.compose.multiplatform)
    alias(libs.plugins.compose.compiler)
}

// The web app (plan D16): the shared Compose app on Kotlin/JS, published to Cloudflare Pages at
// /app/ under the website (website/README.md).
//   ./gradlew :webApp:jsBrowserDevelopmentRun     http://localhost:8080
//   ./gradlew :webApp:site                        the whole site, in build/site

val localProps = Properties().apply {
    rootProject.file("local.properties").takeIf { it.exists() }?.inputStream()?.use { load(it) }
}

fun secret(name: String): String = localProps.getProperty(name) ?: System.getenv(name) ?: run {
    logger.warn("WARNING: $name is not set in local.properties or the environment; builds will use an empty value.")
    ""
}

// Settings the app reads at start-up, like Android's BuildConfig
val generateWebBuildConfig by tasks.registering {
    val versionName = findProperty("versionName") as String? ?: "2.0"
    val uploadUrl = secret("PHOTO_UPLOAD_URL")
    val out = layout.buildDirectory.dir("generated/webBuildConfig")
    inputs.property("versionName", versionName)
    inputs.property("uploadUrl", uploadUrl)
    outputs.dir(out)
    doLast {
        val file = out.get().file("WebBuildConfig.kt").asFile
        file.parentFile.mkdirs()
        file.writeText(
            """
            |// Generated by webApp/build.gradle.kts
            |internal object WebBuildConfig {
            |    const val VERSION_NAME = "$versionName"
            |    const val PHOTO_UPLOAD_URL = "$uploadUrl"
            |}
            |""".trimMargin(),
        )
    }
}

// Served next to index.html: the catalog and model the app falls back to when none is published,
// and LiteRT.js's WebAssembly runtime (from node_modules, after the npm install)
val webContent by tasks.registering(Sync::class) {
    dependsOn(":kotlinNpmInstall")
    from(rootProject.file("androidApp/assets")) { include("herb_catalog.csv", "herb_model.tflite") }
    from(rootProject.layout.buildDirectory.dir("js/node_modules/@litertjs/core/wasm")) {
        // The threaded and JSPI builds need cross-origin isolation or flags; the plain build is enough
        include("litert_wasm_internal.*", "litert_wasm_compat_internal.*")
        into("litert")
    }
    into(layout.buildDirectory.dir("generated/webContent"))
}

kotlin {
    js {
        browser {
            commonWebpackConfig { outputFileName = "herblens.js" }
        }
        binaries.executable()
    }
    sourceSets {
        jsMain {
            kotlin.srcDir(generateWebBuildConfig)
            resources.srcDir(webContent)
            dependencies {
                implementation(projects.composeApp)
            }
        }
    }
}

val REPOSITORY = "https://github.com/trientran/oriental-herb-lens"

// The About pages, made from the repository's READMEs so they can't differ: everything above the
// "about:end" marker, in the site's header and footer (website/about.template.html); about.html from
// README.md and about-vi.html from README.vi.md. Links to files in the repository point at GitHub.
// The build fails if the two READMEs have different sections or links, so neither falls behind.
val aboutPage by tasks.registering {
    val root = rootProject.layout.projectDirectory
    val english = root.file("README.md")
    val vietnamese = root.file("README.vi.md")
    val template = root.file("website/about.template.html")
    val out = layout.buildDirectory.dir("generated/about")
    inputs.files(english, vietnamese, template)
    outputs.dir(out)
    doLast {
        fun intro(file: RegularFile) = file.asFile.readText().substringBefore("<!-- about:end")
        fun sections(markdown: String) = markdown.lines().count { it.startsWith("## ") }
        fun links(markdown: String) = Regex("""\]\(([^)]+)\)""").findAll(markdown).map { it.groupValues[1] }
            .filterNot { it.startsWith("README") }.toSortedSet()
        val en = intro(english)
        val vi = intro(vietnamese)
        check(sections(en) == sections(vi) && links(en) == links(vi)) {
            "README.md and README.vi.md differ above about:end (sections ${sections(en)} vs ${sections(vi)}; " +
                "links only in one: ${(links(en) - links(vi)) + (links(vi) - links(en))}). Update both."
        }
        val parser = Parser.builder().build()
        val renderer = HtmlRenderer.builder().build()
        fun page(markdown: String, lang: String, title: String, description: String, footer: String): String {
            val body = renderer.render(parser.parse(markdown))
                .replace("href=\"README.vi.md\"", "href=\"about-vi.html\"")
                .replace("href=\"README.md\"", "href=\"about.html\"")
                .replace(Regex("href=\"(?!https?:|mailto:|#|about)([^\"]+)\""), "href=\"$REPOSITORY/blob/master/$1\"")
            return template.asFile.readText()
                .replace("{{lang}}", lang).replace("{{title}}", title).replace("{{description}}", description)
                .replace("{{footer}}", footer).replace("{{content}}", body.trim())
        }
        val contact = """<a href="mailto:ttran72@myune.edu.au">ttran72@myune.edu.au</a> · <a href="mailto:tptrien@gmail.com">tptrien@gmail.com</a>"""
        val dir = out.get().asFile.apply { mkdirs() }
        dir.resolve("about.html").writeText(
            page(
                en, "en", "About Med Herb Lens",
                "Med Herb Lens: identify medicinal herbs with your camera, browse 4,799 species and train your own models, on Android, iOS and the web. A research project.",
                """<a href="about-vi.html">Tiếng Việt</a> · <a href="pages/privacy-policy.html">Privacy Policy</a> · <a href="pages/terms-of-service.html">Terms of Service</a> · Contact: $contact""",
            ),
        )
        dir.resolve("about-vi.html").writeText(
            page(
                vi, "vi", "Giới thiệu Med Herb Lens",
                "Med Herb Lens: nhận dạng cây thuốc bằng camera, tra cứu 4.799 loài và tự huấn luyện mô hình, trên Android, iOS và web. Một dự án nghiên cứu.",
                """<a href="about.html">English</a> · <a href="pages/privacy-policy.html">Chính sách quyền riêng tư</a> · <a href="pages/terms-of-service.html">Điều khoản dịch vụ</a> (tiếng Anh) · Liên hệ: $contact""",
            ),
        )
    }
}

// The whole site: the home page and legal pages (website/), the About page, with the app at /app/
val site by tasks.registering(Sync::class) {
    from(rootProject.file("website")) { exclude("README.md", "about.template.html") }
    from(aboutPage)
    from(tasks.named("jsBrowserDistribution")) {
        into("app")
        // Webpack bundles Skiko into herblens.js and loads its hashed .wasm: these copies are unused
        exclude("**/*.map", "skiko.wasm", "skiko.mjs", "skikod8.mjs", "js-reexport-symbols.mjs")
    }
    into(layout.buildDirectory.dir("site"))
}
