import java.util.Properties

plugins {
    alias(libs.plugins.kotlin.multiplatform)
    alias(libs.plugins.compose.multiplatform)
    alias(libs.plugins.compose.compiler)
}

// The web app (plan D16): the shared Compose app on Kotlin/JS, published to Cloudflare Pages.
//   ./gradlew :webApp:jsBrowserDevelopmentRun     http://localhost:8080
//   ./gradlew :webApp:jsBrowserDistribution       the site, in build/dist/js/productionExecutable

val localProps = Properties().apply {
    rootProject.file("local.properties").takeIf { it.exists() }?.inputStream()?.use { load(it) }
}

fun secret(name: String): String = localProps.getProperty(name) ?: System.getenv(name) ?: run {
    logger.warn("WARNING: $name is not set in local.properties or the environment; builds will use an empty value.")
    ""
}

// Settings the app reads at start-up, like Android's BuildConfig
val generateWebBuildConfig by tasks.registering {
    val versionName = findProperty("versionName") as String? ?: "1.1"
    val uploadUrl = secret("PHOTO_UPLOAD_URL")
    val out = layout.buildDirectory.dir("generated/webBuildConfig")
    inputs.property("versionName", versionName)
    inputs.property("uploadUrl", uploadUrl)
    outputs.dir(out)
    doLast {
        val file = out.get().file("WebBuildConfig.kt").asFile
        file.parentFile.mkdirs()
        file.writeText(
            """
            |// Generated by webApp/build.gradle.kts
            |internal object WebBuildConfig {
            |    const val VERSION_NAME = "$versionName"
            |    const val PHOTO_UPLOAD_URL = "$uploadUrl"
            |}
            |""".trimMargin(),
        )
    }
}

// Served next to index.html: the catalog and model the app falls back to when none is published,
// and LiteRT.js's WebAssembly runtime (from node_modules, after the npm install)
val webContent by tasks.registering(Sync::class) {
    dependsOn(":kotlinNpmInstall")
    from(rootProject.file("androidApp/assets")) { include("herb_catalog.csv", "herb_model.tflite") }
    from(rootProject.layout.buildDirectory.dir("js/node_modules/@litertjs/core/wasm")) {
        // The threaded and JSPI builds need cross-origin isolation or flags; the plain build is enough
        include("litert_wasm_internal.*", "litert_wasm_compat_internal.*")
        into("litert")
    }
    into(layout.buildDirectory.dir("generated/webContent"))
}

kotlin {
    js {
        browser {
            commonWebpackConfig {
                outputFileName = "herblens.js"
                // Leaflet's stylesheet (core:maps)
                cssSupport { enabled.set(true) }
            }
        }
        binaries.executable()
    }
    sourceSets {
        jsMain {
            kotlin.srcDir(generateWebBuildConfig)
            resources.srcDir(webContent)
            dependencies {
                implementation(projects.composeApp)
            }
        }
    }
}
